### ISSUE TITLE
What represents MessagePart::Multipart

### ISSUE THREAD

**Issue by arjentz** [stalwartlabs/mail-parser#10]
I noticed that in your most recent release (0.3.1) you added a variant of `Messagepart`: `Multipart` and I was wondering how I should handle this when rendering attachments. Is there a test case for this?

**Comment by mdecimus** [comment]
The `MessagePart:Multipart` type stores the raw headers of a nested MIME multipart and are never returned by the `Message::get_attachments()` iterator, so you can safely ignore them. The `MessagePart:Multipart` type is only used when accessing the raw MIME structure of the message, which is available in `Message::structure` field. In future releases a method will be added to explore the raw body structure of messages.

**Comment by arjentz** [comment]
Thank you! I saw that in 0.4.0 you re-added `MessagePart::InlineBinary`, can that one also be ignored when rendering attachments? I'm currently only rendering the `text_body` and all attachments, but I was wondering if anything (other than the HTML markup) would get lost that way.

**Comment by mdecimus** [comment]
Inline binaries are embeddable content (such as images or videos) which are part of an HTML or text body. It is up to you if you want to render these as attachments, but most email clients do not consider these attachments since they are part of the message body. Hope it helps!

**Comment by arjentz** [comment]
Well, I was wondering if these'll show up in `Message::get_attachments` or not

**Comment by mdecimus** [comment]
Yes, they will show up in `get_attachments`.
