### ISSUE TITLE
Parsing mbox files?

### ISSUE THREAD

**Issue by onthebridgetonowhere** [stalwartlabs/mail-parser#11]
The library is great, thanks for putting it together! I was wondering if there are plans to have a parser for reading&parsing files in mbox format?

**Comment by mdecimus** [comment]
Hi, thanks! I wasn't planning on supporting mbox but it could be a nice addition. I'll keep the issue open and as soon as I have some spare time I'll add the functionality. It shouldn't take too much time to implement it.

**Comment by onthebridgetonowhere** [comment]
Thanks for the update, that'd be fantastic. If you start on it, I can maybe help with some PRs as well. Let me know! 
Just for context, I need to parse emails from the  [apache mailing list](http://mail-archives.apache.org/mod_mbox/), which I have them stored as `mbox` files.

**Comment by mdecimus** [comment]
Hi, I just pushed to master the MBox parser as well as an example under the `examples/` folder. Please, could you give it a quick test before I release it to crates.io? Thanks!

**Comment by onthebridgetonowhere** [comment]
@mdecimus - fantastic, thank you! I've tried it out on more than 20k mbox files, totaling over 4M emails. Seems to work fine, at least for my case. There are some weird&infrequent corner cases where people copy paste emails (including all the metadata) and paste them in the body of the email; however, these are really hard to detect so this is good enough for me. I hope mail-parser becomes more popular and the standard way of parsing emails in Rust, it works really nice so far!

**Comment by mdecimus** [comment]
> There are some weird&infrequent corner cases where people copy paste emails (including all the metadata) and paste them in the body of the email

That is probably a bug in the process that generated the mbox file. When writing a message to an mbox file, any lines beginning with `From `  should be escaped with a `>` symbol (for details here is the [specification](http://qmail.org/qmail-manual-html/man5/mbox.html)). Another alternative is that your mbox file was escaped using a different algorithm (i.e. adding the number of bytes to be read somewhere in the From header), if that is the case please send me a few samples and I'll add support for it.

>  I hope mail-parser becomes more popular and the standard way of parsing emails in Rust, it works really nice so far!

Thanks, I hope that too!
