### ISSUE TITLE
Make Datetime sortable?

### ISSUE THREAD

**Issue by alexwennerberg** [stalwartlabs/mail-parser#13]
I'm trying to sort a list of emails by datetime, and it appears the DateTime struct doesn't allow this -- what do you think the best solution is for this?

**Comment by mdecimus** [comment]
The quickest solution would be converting the date to a ISO8601 string using `Message::get_date().unwrap().to_iso8601()`. Alternatively you could use the `chrono` crate to convert the date to a timestamp, or sort directly the chrono object.

**Comment by alexwennerberg** [comment]
Would you accept a PR that converted this datetime object to unix time? I'm trying to avoid pulling in chrono as a dependency @mdecimus

**Comment by mdecimus** [comment]
Ok, I'll add this feature as soon as I have some free time this week. I found a neat algorithm for this:
https://github.com/protocolbuffers/upb/blob/22182e6e/upb/json_decode.c#L982

**Comment by mdecimus** [comment]
Done, v.0.4.5 is out with support for timestamp conversion and sorting by DateTime.
