### ISSUE TITLE
Message::parse() panics!

### ISSUE THREAD

**Issue by arifd** [stalwartlabs/mail-parser#14]
Hi guys,

Great little library!! But...

This example:
```rust
use mail_parser::Message;

const INPUT: &[u8; 314] = br#"From: <redacted@flashmail.net>
Subject: Redacted
To: <redacted@Enron.com>
Message-ID: <105647271315.NCV17523@x263.net>
MIME-version: 1.0
Content-Type: text/html;
 charset=utf-8
Content-Disposition: =?utf-8?Q?invalid?=
Content-Transfer-Encoding: quoted-printable
Content-Disposition: =?utf-8?Q?invalid?=

<p>foo</p>"#;

fn main() {
    let message = Message::parse(INPUT);
    dbg!(message);
}
```
Will panic with this message:
```
thread 'main' panicked at 'HeaderValue::get_content_type called on non-ContentType value', /home/arif/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.4.4/src/lib.rs:693:18
```
despite `Message::parse` advertising it never will; and that it does a best effort.

Could we have a look into it? Thanks!

**Comment by mdecimus** [comment]
Hi, that was actually a bug, thanks for the report! I've just committed the fix to the repository, please could you give it a try?

**Comment by arifd** [comment]
confirmed! Thank you!

**Comment by arifd** [comment]
hey @mdecimus, been waiting for a minor release update on crates. You don't think a bugfix is worth the PATCH version update, as outlined by https://semver.org/?

**Comment by arifd** [comment]
Thank you! Incredibly responsive!!
