### ISSUE TITLE
owned version of `Message`

### ISSUE THREAD

**Issue by alexwennerberg** [stalwartlabs/mail-parser#18]
Is there a way to create an owned version of `Message`, or some idiomatic way of wrapping around it?

I have a function basically like:

```rust
impl MailStore {
    fn get(&self) -> Message {
        let data = std::fs::read(self.data).unwrap()
        let msg = Message::parse(&data).unwrap()
    }
}
```

But this doesn't work, of course, because `Message` references the owned data. What's a better way of doing this?

**Comment by mdecimus** [comment]
Not really, the library tries to be as efficient as possible and avoids copying/owning data from the raw message. In your case you could create your own Message struct containing the owned data, or a simpler alternative would be to return the Vec<u8> containing the raw message and do the parsing outside MailStore.

**Comment by alexwennerberg** [comment]
Those where the two solutions i came up with. I’ll experiment with them. Thanks
