### ISSUE TITLE
Feature to not use `unsafe`

### ISSUE THREAD

**Issue by dcormier** [stalwartlabs/mail-parser#2]
I would gladly accept a performance penalty in exchange for not using `unsafe` code. If there were use a feature on this crate, I would use it. As it stands, I cannot use this library because of the use of `unsafe`.

**Comment by mdecimus** [comment]
Done! Just released version 0.2.0 with **100% safe Rust code**. 
hanks once again for your constructive feedback.

**Comment by robinkrahl** [comment]
Great, thank you!  Now you could even add `#[forbid(unsafe_code)]` to `lib.rs` to make it more explicit that the crate is not using unsafe code.

**Comment by mdecimus** [comment]
Perfect, thanks!
