### ISSUE TITLE
License issue?

### ISSUE THREAD

**Issue by superboum** [stalwartlabs/mail-parser#24]
You state in your README file that mail-parser is distributed either under the MIT or Apache 2 license, at my own discretion.
But at the same time, you have a `COPYING` file that state your project is distributed under the BSD-2  license, and this is what Github decides to advertise. In my case, I think that these 3 licenses are great but it is hard to really identify which license applies :-)

ps: thanks for your amazing work!

**Comment by mdecimus** [comment]
Thanks, fixed!
