### ISSUE TITLE
Check if parsed message is empty

### ISSUE THREAD

**Issue by robinkrahl** [stalwartlabs/mail-parser#3]
I would like to be able to check whether `Message::parse` was able to parse anything at all so that I can fail early on invalid input.  As far as I see, I currently have to call all getter methods and check their return values.  What do you think about having a `Message::is_empty` method for this use case?

**Comment by mdecimus** [comment]
Done! `Message::is_empty` has been added to version 0.2.0 which also has 100% safe Rust code!
Thanks.

**Comment by robinkrahl** [comment]
Thank you!
