### ISSUE TITLE
Add possibility of finding out where parsing ended

### ISSUE THREAD

**Issue by jsjolen** [stalwartlabs/mail-parser#34]
Hi!

I have a Mailman archive (I'm pretty sure that this is in Mbox format?) that I'd like to parse. I've succesfully used `Message::parse(&[u8])` to parse the first e-mail in the file, and I've used the Mbox iterator to parse every e-mail in the file.

OK, cool! But the parse results from the Mbox iterator have far less detail (and API surface) as compared to the results from `Message::parse`. Can I iterate over a file, parsing `Message`s as I go along? As `Message::parse` doesn't tell me where parsing stopped, this seems impossible to me.

Seems like a solution is to provide `_parse()` with the `MessageStream` and return the final `pos` and `Message` when done parsing.

What do you think?

Cheers,
Johan

**Comment by mdecimus** [comment]
Hi,

Using ``MessageStream`` directly won't be possible unfortunately as the Mbox format requires all lines starting with "From " to be prefixed with a ">". That is why ``MessageIterator`` first has to remove these prefixes before the message can be fed to ``Message::parse``. What could be done is to add to ``MessageIterator`` a method to obtain the current offset within the Mbox file. Would this help?

**Comment by jsjolen** [comment]
Hm, wouldn't this work:

```rust
    fn parse_(raw_message: &'x [u8], depth: usize) -> Option<Message<'x>> {
// Instead:
    fn parse_(offset: usize, raw_message: &'x [u8], depth: usize) -> Option<Message<'x>, MessageStream<'x>>
// New function:
pub fn parse_from_offset(offset: usize, raw_message: &'x[u8]) -> Option<Message<'x>, MessageStream<'x>>

// Change ctr of MessageStream
impl<'x> MessageStream<'x> {
    pub fn new(data: &'x [u8], pos: usize) -> MessageStream<'x> {
```

That seems like it would work and be a minimal amount of work? Yeah, the user has to mess about with the MessageStream, but a future PR could always implement an iterator that does that for you.

**Comment by jsjolen** [comment]
Btw, I am not all that familiar with the e-mail RFCs. I know they're apparently a pain, though :).

All I know is that I have a file of what seems like concatenated e-mails, and I'd like the Message parser to not throw away where in the file it stopped parsing, so I can continue on at that point.

**Comment by mdecimus** [comment]
There is no need to add a new function to start parsing from an offset, you can do that with Rust like this:

```rust
let message = Message::parse(&bytes[offset..]).unwrap();
```

**Comment by mdecimus** [comment]
The problem with using offsets in an mbox file is that the messages inside this file are escaped. The details of this process is [described here](http://qmail.org/man/man5/mbox.html) but basically it does the following:

>           Here is how a program appends a message to an mbox file.
>           It first creates a From_ line given the message's envelope
>           sender and the current date.  If the envelope sender is
>           empty (i.e., if this is a bounce message), the program uses
>           MAILER-DAEMON instead.  If the envelope sender contains
>           spaces, tabs, or newlines, the program replaces them with
>           hyphens.
> 
>           The program then copies the message, applying >From quoting
>           to each line.  >From quoting ensures that the resulting
>           lines are not From_ lines:  the program prepends a > to any
>           From_ line, >From_ line, >>From_ line, >>>From_ line, etc.
> 
>           Finally the program appends a blank line to the message.  If
>           the last line of the message was a partial line, it writes
>           two newlines; otherwise it writes one.

Messages inside an mbox first need to be located using the ``From_`` line and then processed to remove the ``>`` prefixes. This means that an offset within an ``mbox`` file cannot be used directly on ``Message::parse`` as it will return invalid data.
What I was proposing above is that ``MessageIterator`` makes available the offset within the mbox file so whatever caused the parsing error could be corrected.
