### ISSUE TITLE
Serialized representation without message body

### ISSUE THREAD

**Issue by pstch** [stalwartlabs/mail-parser#37]
Hi again,

I've done a bit of integration of mail-parser into my MLM project, but I had to make a few modifications to the library's code to make it fit my needs, and would like advise on how I could integrate these features to the library in the long term.

Namely, I need to serialize `Message` without the raw message, so that I can retrieve both the serialization and raw message from storage, and quickly build a `Message` from that, without having to run the parser again. Depending on the situation, I may need a byte-for-byte copy of most the original message (for DKIM-friendly semantics), but in other cases I will only  be looking at parts of it, and in all cases I need to read the metadata, and store all of that in distributed storage (that may be different for metadata and raw message). For simplicity, I chose to keep storing header values inline.

For example, the changes I've had to make were :
 - use custom (de-)serialization for MessagePart to only store the discriminant of PartType
   + here I also keep Encoding in the serialization
 - use custom (de-)serialization for Message to store a hash of the raw message, that is matched with the raw message provided when deserializing

I still need to continue testing to see if there's anything I missed, and there's a bit of work remaining to keep the existing (de-)serialization work as it did.

Do you think it would be possible to integrate this in `mail-parser` ? I'm ok with maintaining my own fork, but I do think it would be a valuable feature. I plan on making it an additional feature flag, that doesn't change the existing (de-)serialization, but I still have to figure out how to make this possible with serde.

**Comment by mdecimus** [comment]
Hi,

> Namely, I need to serialize `Message` without the raw message

Currently mail-parser is serializing `Message` **without** the raw message:

```rust
pub struct Message<'x> {
    #[cfg_attr(feature = "serde_support", serde(default))]
    pub html_body: Vec<MessagePartId>,
    #[cfg_attr(feature = "serde_support", serde(default))]
    pub text_body: Vec<MessagePartId>,
    #[cfg_attr(feature = "serde_support", serde(default))]
    pub attachments: Vec<MessagePartId>,

    #[cfg_attr(feature = "serde_support", serde(default))]
    #[cfg_attr(feature = "serde_support", serde(borrow))]
    pub parts: Vec<MessagePart<'x>>,

    #[cfg_attr(feature = "serde_support", serde(skip))]
    pub raw_message: Cow<'x, [u8]>,
}
```

As you can see above there is a `serde(skip)` directive on raw_message.

**Comment by pstch** [comment]
Ah, sorry, I didn't explain myself properly. When I meant without the raw message, I meant also without the part contents, which would be recovered using the part offsets when deserializing. In essence, I'd like to have a message serialization format that only includes the message structure and headers, but not its contents.

**Comment by mdecimus** [comment]
I understand now! I don't think it is necessary to keep your own fork for this change, you could write a custom [de]serializer that skips the contents of each message part.

**Comment by pstch** [comment]
So I've made a bit of progress on this, and using solely custom [de]serializers is not enough, because it's hard to propagate context across the structure using serde.  Instead, I  wrote some adaptor strucs (`CompactMessage`, `CompactMessagePart`, `CompactPartType`) and impls to convert from/to `Message`. You can see the result [here](https://gist.github.com/pstch/81c28d81c9b4f4e04d6d55cc2c711067) if you're interested. I think nested encodings are not properly handled yet.

I realized that yeah it's maybe not the best fit for this library, as defining an AST for a format that allows nested encodings is not very practical.
