### ISSUE TITLE
Message.raw_message returns the root message instead of the selected one.

### ISSUE THREAD

**Issue by superboum** [stalwartlabs/mail-parser#38]
## Bug

When I call `raw_message()` on a Message object obtained from a `PartType::Message(nested_message)` call, I get the root message buffer and not the buffer.

## Expected

When calling `raw_message()`, I expect getting the buffer associated to the message object (ie. the buffer corresponding to the selected part).

## Regression

In v0.5.0 (and earlier), `raw_message()` was returning the buffer associated to the message object, as expected.

## Context

Here is a simple example to reproduce the unexpected behavior:

```rust
use mail_parser::*;

fn main() {
    let input = br#"From: root <root@example.com>
Content-Type: multipart/mixed; boundary="delim";
Subject: root subject

--delim
Content-Type: text/plain; charset="us-ascii"

root part
--delim
Content-Type: message/rfc822

From: inner <inner@example.com>
Subject: inner subject

inner part

--delim--
"#;

    let root_message = Message::parse(input).unwrap();
    let inner_message = &root_message.parts[2].message().unwrap();
    println!("raw message: {}...", String::from_utf8_lossy(&inner_message.raw_message[0..24]));
}
```

And the result it returns:

```
raw message: From: root <root@example...
```

And the result I expect:

```
raw message: From: inner <inner@example...
```

**Comment by mdecimus** [comment]
Please upgrade to version `0.8.1`. A new function `raw_message()` was added to access the raw message contents. Use this function instead of the struct element.
