### ISSUE TITLE
`Message::message_id()` returns message id without `<` and `>`

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-parser#42]
According to [RFC 2822](https://www.rfc-editor.org/rfc/rfc2822), the `<` and the `>` are part of the `msg-id` definition `[CFWS] "<" id-left "@" id-right ">" [CFWS]` and should therefore be included in the message id itself.

**Comment by mdecimus** [comment]
Some clients do not include the brackets in message IDs (even though RFC5322 requires them) so to standarize the IDs the library returns them without brackets. If you require the brackets in your app you can concatenate them to the returned string.

**Comment by soywod** [comment]
> Some clients do not include the brackets in message IDs (even though
> RFC5322 requires them) so to standarize the IDs the library returns
> them without brackets.

It makes sense! It could be nice to leave a note somewhere in the doc
about this, because it took me a while to debug the issue (I work on an
email synchronizer that heavily relies on `Message-ID`).

> If you require the brackets in your app you can concatenate them to
> the returned string.

It is the solution I implemented meanwhile, I will leave it like this.

Thank you!

**Comment by soywod** [comment]
Is the same logic should apply to `In-Reply-To` header? If I have a message with `Message-ID: <test@localhost>`, and I do sth like:

```rust
if let Some(message_id) = parsed.header_raw("Message-ID") {
    builder = builder.in_reply_to(format!("<{message_id}>"));
}
```

Then the built message will have `In-Reply-To: test@localhost` instead of `In-Reply-To: <test@localhost>`, which breaks the thread because ids are not strictly equal.

**Comment by soywod** [comment]
BTW, I think that `.header_raw()` should return the raw value without any treatment. In case of `Message-ID` or `In-Reply-To` it should return the original version (with or without `< >`) in order to prevent thread mismatch.

**Comment by mdecimus** [comment]
> Is the same logic should apply to In-Reply-To header? If I have a message with Message-ID: <test@localhost>

Yes, the following headers are parsed as Ids:

```
RfcHeader::MessageId
RfcHeader::References
RfcHeader::InReplyTo
RfcHeader::ReturnPath
RfcHeader::ContentId
RfcHeader::ResentMessageId
```
