### ISSUE TITLE
Missing space when folded header begins with RFC2047 word

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-parser#43]
According to [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322#section-2.2.3):

>   For example, the header field:
>
> ```
> Subject: This is a test
> ```
>
>   can be represented as:
>
> ```
> Subject: This
>  is a test
> ```
> […]
>
> Unfolding is accomplished by simply removing any CRLF that is immediately followed by WSP.  Each header field should be treated in its unfolded form for further syntactic and semantic evaluation.

For example, I have an email with this header:

```
Subject: Les Communs - =?utf-8?Q?R=C3=A9capitulatif?= de la
 =?utf-8?Q?r=C3=A9servation?= 13510164434879
```

It is parsed and unfolded as:

```
Les Communs - Récapitulatif de laréservation 13510164434879
                                 ╏
                                 ┗ space missing here
```

Instead of:

```
Les Communs - Récapitulatif de la réservation 13510164434879
```

**Comment by mdecimus** [comment]
Just committed a fix, please let me know if it fixes it. Thanks.

**Comment by soywod** [comment]
Yes it works well, thank you! Would it be possible to release a new
minor version?

**Comment by mdecimus** [comment]
Done, `0.8.2` is out!
