### ISSUE TITLE
Interop between mail-parser and mail-builder

### ISSUE THREAD

**Issue by katyo** [stalwartlabs/mail-parser#44]
Thanks for awesome `mail-parser` and `mail-builder` crates!
I developing a tool which modifies mails so I need a way to build parsed emails back.
Have you any plans to support such usage scenario?

**Comment by mdecimus** [comment]
Hi,

There are no plans to integrate both libraries, but what you could do to build a parsed email back is take the raw offsets of the parts that you want to modify and then re-generate the message replacing those offsets with the modified content. You can take a look at the `sieve` crate that does exactly that, it lets scripts add, modify or remove headers and MIME parts. You can take a look at the [Replace](https://github.com/stalwartlabs/sieve/blob/main/src/runtime/actions/action_mime.rs#L43) and [Enclose](https://github.com/stalwartlabs/sieve/blob/main/src/runtime/actions/action_mime.rs#L180) functions to see an example.
