### ISSUE TITLE
Two Digit Year in Date Headers

### ISSUE THREAD

**Issue by thejereman13** [stalwartlabs/mail-parser#47]
[RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-4.3) states that a 2-digit year between 0-49 should be parsed as 2000-2049, but it looks like this library is mapping all 2-digit years to the 1900s instead.

An example of such header is:
`Date: 12 May 23 00:00:05 -0800`

**Comment by sftse** [comment]
I ran into an example of this in the wild.
