### ISSUE TITLE
Method `html_bodies()` with non-expected behavior.

### ISSUE THREAD

**Issue by lemunozm** [stalwartlabs/mail-parser#51]
Hi! Thanks for this crate! 🚀 

I wanted to notify about a non-expected (at least for me) behavior in the parsing.

The `html_bodies()` method returns an iterator that iterates over parts with "text/html" (ok), but also for parts with "text/plain". I understand in this case, we do not want to interpret the "text/plain" parts as HTML.

Am I right?

**Comment by mdecimus** [comment]
Body parts are grouped using the algorithm described in [RFC8621, section 4.1.4](https://datatracker.ietf.org/doc/html/rfc8621#autoid-35). If you would like to use a different algorithm you can iterate Message::parts directly.

**Comment by lemunozm** [comment]
Ok, I already see. Thanks for your fast answer!
