### ISSUE TITLE
`.header_raw()` on `Message-ID` or `In-Reply-To` skips `<` and `>`

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-parser#53]
As discussed here #42, `.header("Message-ID")` returns the message identifier without `<` and `>`. But I expect `.header_raw("Message-ID")` to return the original string. I try to build a reply template from a parsed email and I cannot properly set up the `In-Reply-To` header because of this issue: the original message `Message-ID` and the reply template `In-Reply-To` should be strictly the same otherwise it breaks threads.

**Comment by mdecimus** [comment]
Do you have a test message I could use to reproduce this? The `.header_raw()` logic does not treat IDs headers differently, it should include the raw contents from the colon until the [CR]LF.

**Comment by soywod** [comment]
While creating a reproducible example I was not able to reproduce the same behaviour so I guess it comes from my implementation. I will dig and reopen if I find the cause.
