### ISSUE TITLE
Non RFC headers encoded words not decoded

### ISSUE THREAD

**Issue by BenJeau** [stalwartlabs/mail-parser#55]
Hi, thanks for such a great library! I've found the following happening within my application.

Headers that are not deemed RFC according to the library, such as `Authentication-Results` (https://datatracker.ietf.org/doc/html/rfc7601) or more proprietary Microsoft headers `X-Microsoft-Antispam-Message-Info` or `X-SID-PRA` do not try to decode content based on https://datatracker.ietf.org/doc/html/rfc2047.

On my end I'm basically doing an additional pass on the values with the `decode_rfc2047()` method from `MessageStream`, but I think this would be better to be part of the library?

It seems like we need to modify `parse_raw()` https://github.com/stalwartlabs/mail-parser/blob/154591697f7ac92326fa7c532e1827e87ae8d30d/src/parsers/fields/raw.rs#L15 from `MessageStream` to conditionally call that `decode_rfc2047()` similarly to `parse_unstructured()` https://github.com/stalwartlabs/mail-parser/blob/154591697f7ac92326fa7c532e1827e87ae8d30d/src/parsers/fields/unstructured.rs#L75 or `parse_address()` https://github.com/stalwartlabs/mail-parser/blob/154591697f7ac92326fa7c532e1827e87ae8d30d/src/parsers/fields/address.rs#L279 or `parse_comma_separared()` https://github.com/stalwartlabs/mail-parser/blob/154591697f7ac92326fa7c532e1827e87ae8d30d/src/parsers/fields/list.rs#L90 or `parse_content_type()` https://github.com/stalwartlabs/mail-parser/blob/154591697f7ac92326fa7c532e1827e87ae8d30d/src/parsers/fields/content_type.rs#L412

If you're open to a pull request/change, let me know :)

**Comment by mdecimus** [comment]
Hi,

I've just pushed a commit that includes a new `header_as` method:

```
pub fn header_as(&self, header_name: &str, form: HeaderForm) -> Vec<HeaderValue>;
```

You can use it as follows:

```
let headers = message.header_as("Authentication-Results", HeaderForm::Text);
```
