### ISSUE TITLE
When is a HeaderValue a TextList(_)?

### ISSUE THREAD

**Issue by dcfreire** [stalwartlabs/mail-parser#56]
Hello,

I'm writting a small library for personal use that implements some functions to convert the parsed `Message` instances of this library, to `MessageBuilder` instances from your other library, mail-builder. Right now I'm writting some code to convert a `mail_parser::HeaderValue` instance to `mail_builder::headers::HeaderType` instance. However I'm not sure what I should to about `mail_parser::HeaderValue::TextList`. What header will produce this value? 

The function `MessageStream::parse_comma_separared` seems to indicate that a comma separated string will produce a `TextList`, but by parsing an eml with such a string, the final parsed `Message` has a `Text` wrapping the full string.

For instance adding a header to an eml `FakeHeader: 1, 2, 3` and parsing it with `Message::parse`, produces the `HeaderValue`:  `Text("1, 2, 3")`.

**Comment by mdecimus** [comment]
Hi,

`TextList` is returned for certain structured headers that have comma separated entries such as `Message-ID` or `Keywords`. However, if the header does not contain multiple entries a `Text` value is returned instead. You can rebuild these header by concatenating all `TextList` entries with a comma. However, if you do not need to do any processing on these headers it is recommended that instead you just copy the raw header values.

**Comment by dcfreire** [comment]
I see, thanks for the clarification.

Just to confirm that I understand your suggestion on copying the raw header values, you're suggesting that I iterate over the raw headers with `Message::headers_raw()` and add the header to the builder with `MessageBuilder::header(name, HeaderType::Raw(header_value))`?

Note: This works for the `Message` headers, but not for the attachment headers, since `MessagePart` does not provide a way for getting the raw headers (I think). So for the attachments I'd still have to write a conversion function.

**Comment by mdecimus** [comment]
> Just to confirm that I understand your suggestion on copying the raw header values, you're suggesting that I iterate over the raw headers with Message::headers_raw() and add the header to the builder with MessageBuilder::header(name, HeaderType::Raw(header_value))?

Yes, that is correct.

> Note: This works for the Message headers, but not for the attachment headers, since MessagePart does not provide a way for getting the raw headers (I think). So for the attachments I'd still have to write a conversion function, although I could convert every HeaderValue to a HeaderType::Raw, I suppose.

You can use the [headers()](https://github.com/stalwartlabs/mail-parser/blob/main/src/lib.rs#L1547) function to obtain the headers of a `MessagePart`. Then use the header offsets to obtain their raw contents.
