### ISSUE TITLE
how to cache parsed email with 'x lifetime of Message?

### ISSUE THREAD

**Issue by bamthomas** [stalwartlabs/mail-parser#59]
First thanks for your rust mail repositories. We are also thinking that the mail is an important part of the internet and it has been disregarded in favour of the web/http.

It's more a rust question than an issue with the library, but I don't know how to  find a solution.

With the declaration : 

```rust
impl<'x> Message<'x> {
    pub fn parse(raw_message: &'x [u8]) -> Option<Message<'x>> {
        // ...
    }
}
```

The `raw_message` reference has a lifetime linked to the `Message` and that makes sense.

I'm trying to parse a list of messages on disk and cache them in a vector : 

```rust
pub struct MessageCache<'x> {
    mail_dir: String,
    messages: Vec<Box<Message<'x>>>
}

impl <'x> MessageCache<'x> {
    pub fn load_messages(&mut self) -> () {
        let paths = fs::read_dir(&self.mail_dir).unwrap();
        for path in paths {
            let path = path.unwrap().path();
            let contents = fs::read(path).unwrap();
            let message = Message::parse(contents.as_slice()).unwrap();
            self.messages.push(Box::new(message));
        }
}
```
And you probably see the issue: the borrow checker is complaining that I can't borrow the value `contents.as_slice()` because it is not living after the `load_messages` method, that would make a dangling reference.

So my question is: how to you transfer the ownership of the message content to the message?

**Comment by mdecimus** [comment]
Hi,

You can use the `Message::into_owned` method which will convert all string reference into owned strings.

**Comment by bamthomas** [comment]
haha yes it works. Thank you for your reply.
