### ISSUE TITLE
Error with the library

### ISSUE THREAD

**Issue by daraccrafter** [stalwartlabs/mail-parser#62]
error[E0369]: binary operation `==` cannot be applied to type `HashMap<HeaderName<'_>, for<'a, 'x> fn(&'a mut MessageStream<'x>) -> HeaderValue<'x>>`
#11 419.3    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.9.0/src/lib.rs:264:5
#11 419.3     |
#11 419.3 262 | #[derive(Debug, PartialEq, Eq, Clone)]
#11 419.3     |                 --------- in this derive macro expansion
#11 419.3 263 | pub struct MessageParser {
#11 419.3 264 |     pub(crate) header_map: HashMap<HeaderName<'static>, HdrParseFnc>,
#11 419.3     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 419.3     |
#11 419.3     = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
#11 419.3 
#11 419.3 error[E0369]: binary operation `==` cannot be applied to type `for<'a, 'x> fn(&'a mut MessageStream<'x>) -> HeaderValue<'x>`
#11 419.3    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.9.0/src/lib.rs:265:5
#11 419.3     |
#11 419.3 262 | #[derive(Debug, PartialEq, Eq, Clone)]
#11 419.3     |                 --------- in this derive macro expansion
#11 419.3 ...
#11 419.3 265 |     pub(crate) def_hdr_parse_fnc: HdrParseFnc,
#11 419.3     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#11 419.3     |
#11 419.3     = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
#11 419.3 help: use parentheses to call these
#11 419.3     |
#11 419.3 265 |     ((pub(crate) def_hdr_parse_fnc: HdrParseFnc)(/* &mut MessageStream<'_> */))(/* &mut MessageStream<'_> */),
#11 419.3     |     +                                          +++++++++++++++++++++++++++++++

**Comment by mdecimus** [comment]
Upgrade to rust latest and try again.
