### ISSUE TITLE
error[E0369]: binary operation `==` cannot be applied to type `HashMap<HeaderName<'_>, for<'a, 'x> fn(&'a mut MessageStream<'x>) -> HeaderValue<'x>>`

### ISSUE THREAD

**Issue by devimalka** [stalwartlabs/mail-parser#64]
when i try to install the mail-parser 0.9.1 i do get the following error

**Compiling mail-parser v0.9.1
error[E0369]: binary operation `==` cannot be applied to type `HashMap<HeaderName<'_>, for<'a, 'x> fn(&'a mut MessageStream<'x>) -> HeaderValue<'x>>`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.9.1/src/lib.rs:264:5
    |
262 | #[derive(Debug, PartialEq, Eq, Clone)]
    |                 --------- in this derive macro expansion
263 | pub struct MessageParser {
264 |     pub(crate) header_map: HashMap<HeaderName<'static>, HdrParseFnc>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `==` cannot be applied to type `for<'a, 'x> fn(&'a mut MessageStream<'x>) -> HeaderValue<'x>`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/mail-parser-0.9.1/src/lib.rs:265:5
    |
262 | #[derive(Debug, PartialEq, Eq, Clone)]
    |                 --------- in this derive macro expansion
...
265 |     pub(crate) def_hdr_parse_fnc: HdrParseFnc,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: use parentheses to call these
    |
265 |     ((pub(crate) def_hdr_parse_fnc: HdrParseFnc)(/* &mut MessageStream<'_> */))(/* &mut MessageStream<'_> */),
    |     +                                          +++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0369`.
error: could not compile `mail-parser` due to 2 previous errors**

**Comment by rostamn739** [comment]
What is your rustc version?
```
rustc --version
```

Mine is 1.72 which compiles this crate good
