### ISSUE TITLE
Address name not quoted and containing a `@` is not properly parsed

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-parser#69]
`To: bob@localhost <bob@localhost>` is parsed as an `Addr` without name but with the following address `bob@localhostbob@localhost`. Technically a `@` is not a valid char in the name (it should be quoted), but since your parser is more flexible and fit better the real world I decided to open the issue. [Here](https://todo.sr.ht/~soywod/pimalaya/159) the original issue opened by a Himalaya user, and here the test I use:

```rust
use concat_with::concat_line;
use mail_parser::MessageParser;

#[test]
fn addresses() {
    let raw_msg = concat_line!(
        "From: alice@localhost",
        "To: bob@localhost <bob@localhost>",
        "Subject: subject",
        "",
        "Hello, world!",
    );

    let msg = MessageParser::new().parse(raw_msg).unwrap();
    let addr = msg.to().unwrap().first().unwrap();

    assert_eq!(addr.address, Some("bob@localhost".into()));
    assert_eq!(addr.name, Some("bob@localhost".into()));
}
```

```bash
running 1 test
test addresses ... FAILED

failures:

---- addresses stdout ----
thread 'addresses' panicked at 'assertion failed: `(left == right)`
  left: `Some("bob@localhostbob@localhost")`,
 right: `Some("bob@localhost")`', mml/tests/addresses.rs:18:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mdecimus** [comment]
Thanks, I'll fix this as soon as possible.

**Comment by soywod** [comment]
I proposed a fixed here: https://github.com/stalwartlabs/mail-parser/pull/80.

**Comment by mdecimus** [comment]
Thanks, merged.

**Comment by soywod** [comment]
Could a new minor version be released so I could publish a new version of mine?

**Comment by mdecimus** [comment]
Done!
