### ISSUE TITLE
Parsing multiline quoted header attributes includes line-wrap-indentation whitespace

### ISSUE THREAD

**Issue by danielwippermann** [stalwartlabs/mail-parser#92]
If a quoted header attribute value breaks into a subsequent line, the whitespace used to indent that subsequent line (to distinguish it from being another header) becomes part of the quoted string.

I encountered that situation with headers similar to this:

```
Content-Disposition: attachment;
<TAB>filename="=?utf-8?Q?Auftragsbest=C3=A4tigung_Xxxxx_Xxxxxx_XXXXXXXXXX=2EPD?=
<SPACE>=?utf-8?Q?F?="
```

After parsing that header the `<SPACE>` from the beginnging of the third line will be part of the attribute value, changing the file extension from `.PDF` to `.PD<SPACE>F`.

The minial test case would be:

```
    #[test]
    fn test_minimal_multiline_quoted_heder_attribute_value() {
        let data = b"Content-Disposition: attachment;\r
\tfilename=\"=?utf-8?Q?Auftragsbest=C3=A4tigung_Xxxxx_Xxxxxx_XXXXXXXXXX=2EPD?=\r
 =?utf-8?Q?F?=\"\r
\r
";

        let mut ms = MessageStream::new(data);
        let hv = ms.parse_content_type();
        let ct = hv.as_content_type().expect("Unable to get ContentType");

        let filename = ct.attribute("filename").expect("Unable to get filename attribute");

        assert_eq!(filename, "Auftragsbestätigung Xxxxx Xxxxxx XXXXXXXXXX.PDF");
    }
```

Which currently (as of commit 0eba00b4e9e2708c4d1b41c09228ef37f820310c) fails:

```
assertion `left == right` failed
  left: "Auftragsbestätigung Xxxxx Xxxxxx XXXXXXXXXX.PD F"
 right: "Auftragsbestätigung Xxxxx Xxxxxx XXXXXXXXXX.PDF"
```

I can skip adding that whitespace by patching the following, but I don't know whether that is the correct way to solve it:

```
diff --git a/src/parsers/fields/content_type.rs b/src/parsers/fields/content_type.rs
index f690f46..57b5095 100644
--- a/src/parsers/fields/content_type.rs
+++ b/src/parsers/fields/content_type.rs
@@ -319,6 +319,7 @@ impl<'x> MessageStream<'x> {
                         ContentState::AttributeQuotedValue => {
                             if next_is_space {
                                 parser.remove_crlf = true;
+                                self.next();
                                 continue;
                             } else {
                                 parser.add_value(self);
```

Edit: Fixed wrong string escaping.

**Comment by mdecimus** [comment]
The correct way to encode multiline continuations is without quotes:

```
Content-Disposition: attachment;
<TAB>filename==?utf-8?Q?Auftragsbest=C3=A4tigung_Xxxxx_Xxxxxx_XXXXXXXXXX=2EPD?=
<SPACE>=?utf-8?Q?F?=
```

In any case, since the goal of the crate is to be flexible while parsing, the library has been fixed to handle this case.

**Comment by danielwippermann** [comment]
Hi @mdecimus !

Thank you for the quick response and solution and dedication. I really enjoyed using your crates! Keep up the good work!

Have a nice weekend!
Daniel
